borgmatic_host_configuration:
  location:
    repositories:
      - type: local
        path: "/srv/backups/{{ inventory_hostname }}"
      - type: remote
        path: "./{{ inventory_hostname }}"
        user: borg
        inventory_host: server
